### ISSUE TITLE
Further contact regarding this app

### ISSUE THREAD

**Issue by LATL9** [chan94306/RubiksCubeSolver#2]
**(There was no public email address for your user, so I am opening an issue instead. Feel free to close afterwards.)**

I am currently in the process of developing an application involving the "scanning" of a Rubik's Cube with a camera.
In this search, I have recently discovered your application, which seems to implement a very similar application.
As part of the research that I am conducting, **I wish to get in contact with you** on how (and why) you created it (a brief explanation will do), with the hope of improving the development of mine too.

Many thanks.

**Comment by Loquats** [comment]
Hey @LATL9. We created this for a school project. The app assumes the user aligns their cube to a grid, shown on screen. The app reads the camera feed, and makes a guess about the colors on each face. Users can correct it, if the guess is incorrect. Feel free to take a look at https://github.com/chan94306/RubiksCubeSolver/blob/master/src/grid/ImageUtilities.java#L23 and the usage of that function.

**Comment by LATL9** [comment]
Thanks! Will take your reply into account when I develop my project. Should also make navigating the source code easier as well (along with added commenting).
